name: clojure-checks
on: [ push ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oxr463/setup-leiningen@0.0.1
      - run: lein test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oxr463/setup-leiningen@0.0.1
      - run: lein lint